// supabase/functions/unsubscribe-contact/index.ts
//
// Public (verify_jwt=false) one-click unsubscribe for contact-list emails.
// The link/token is generated by send-contact-broadcast and signed with the
// service-role key. On a valid token we set organization_contacts.unsubscribed_at
// for (org, player) — creating the link row if the person was a registrant not
// yet on the contact list — so they're excluded from future sends, and we
// credit the originating broadcast's unsubscribe count.
//
// Handles GET (link click → HTML confirmation page) and POST (RFC 8058
// List-Unsubscribe-Post one-click → 200).
//
// Required secrets (auto-injected): SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY.

// @ts-expect-error remote import resolved at runtime by Deno
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { escapeHtml } from "../_shared/email-layout.ts";
import { verifyUnsubToken } from "../_shared/unsubscribe.ts";

// deno-lint-ignore no-explicit-any
type Db = any;

// @ts-expect-error Deno global in edge runtime
Deno.serve(async (req: Request) => {
  if (req.method !== "GET" && req.method !== "POST") {
    return htmlPage("Method not allowed.", 405);
  }
  try {
    // @ts-expect-error Deno env
    const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
    // @ts-expect-error Deno env
    const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const admin: Db = createClient(SUPABASE_URL, SERVICE_KEY);

    const url = new URL(req.url);
    const token = url.searchParams.get("token") ?? "";
    const verified = token ? await verifyUnsubToken(SERVICE_KEY, token) : null;
    if (!verified) {
      return htmlPage("This unsubscribe link is invalid or has expired.", 400);
    }
    const { orgId, playerId, broadcastId } = verified;
    const nowIso = new Date().toISOString();

    // Idempotent opt-out on the org-contact link.
    const { data: existing } = await admin
      .from("organization_contacts")
      .select("unsubscribed_at")
      .eq("organization_id", orgId)
      .eq("player_id", playerId)
      .maybeSingle();

    let alreadyUnsubscribed = false;
    if (existing) {
      alreadyUnsubscribed = !!existing.unsubscribed_at;
      if (!alreadyUnsubscribed) {
        await admin
          .from("organization_contacts")
          .update({ unsubscribed_at: nowIso })
          .eq("organization_id", orgId)
          .eq("player_id", playerId);
      }
    } else {
      // Registrant not yet on the contact list — record the opt-out.
      await admin.from("organization_contacts").insert({
        organization_id: orgId,
        player_id: playerId,
        source: "manual",
        unsubscribed_at: nowIso,
      });
    }

    // Credit the originating broadcast: mark this recipient row unsubscribed.
    // The status page counts unsubscribes by aggregating these timestamps, so
    // there's no rollup counter to race on.
    if (!alreadyUnsubscribed) {
      await admin
        .from("contact_broadcast_recipients")
        .update({ unsubscribed_at: nowIso, last_event_at: nowIso })
        .eq("broadcast_id", broadcastId)
        .eq("player_id", playerId);
    }

    const { data: org } = await admin
      .from("organizations")
      .select("name")
      .eq("id", orgId)
      .maybeSingle();
    const orgName = escapeHtml(org?.name ?? "this club");

    return htmlPage(
      `You've been unsubscribed from <strong>${orgName}</strong> emails.<br />You won't receive further messages from them.`,
      200,
    );
  } catch (e) {
    console.error("unsubscribe-contact error", String((e as { message?: string })?.message ?? e));
    return htmlPage("Something went wrong. Please try again later.", 500);
  }
});

function htmlPage(message: string, status: number): Response {
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Unsubscribe · bert &amp; erne</title></head>
<body style="margin:0;background:#fafaf7;font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;color:#14181f;">
<div style="max-width:520px;margin:64px auto;padding:0 20px;text-align:center;">
  <div style="font-size:22px;font-weight:800;letter-spacing:-0.3px;margin-bottom:16px;">bert &amp; erne</div>
  <div style="background:#fff;border:1px solid #e3dec8;border-radius:12px;padding:28px 24px;font-size:15px;line-height:1.55;color:#4a5159;">
    ${message}
  </div>
</div></body></html>`;
  return new Response(html, {
    status,
    headers: { "Content-Type": "text/html; charset=utf-8" },
  });
}
