#!/usr/bin/env bash
# One-command offline runtime for Bert & Erne (issue #733).
#
# Brings up a LOCAL Supabase stack (Postgres + Auth + the same REST API the
# app already talks to) via the Supabase CLI, points the web app at it
# instead of the hosted project, and starts the dev server. Nothing here
# touches the hosted Supabase project or the deployed app — this is purely
# additive, opt-in tooling (see docs/OFFLINE.md).
#
# ONE-TIME PREREQUISITE (needs network — do this BEFORE going offline):
#   brew install supabase/tap/supabase   # if not already installed
#   supabase start                       # from the repo root; caches the
#                                         # local stack's Docker images once
# After that first run, this script needs no network access.
set -euo pipefail

cd "$(dirname "$0")/.."

if ! command -v supabase >/dev/null 2>&1; then
  echo "error: supabase CLI not found on PATH." >&2
  echo "Install it (brew install supabase/tap/supabase) before going offline." >&2
  exit 1
fi

echo "Starting local Supabase (Postgres + Auth + API)..."
# Idempotent: if the stack is already up, `supabase start` reports that and
# exits non-zero — that's not a failure for us, so don't let set -e kill the
# script over it.
supabase start || true

STATUS_ENV="$(supabase status -o env)"
API_URL="$(printf '%s\n' "$STATUS_ENV" | grep '^API_URL=' | cut -d= -f2- | tr -d '"')"
ANON_KEY="$(printf '%s\n' "$STATUS_ENV" | grep '^ANON_KEY=' | cut -d= -f2- | tr -d '"')"

if [ -z "$API_URL" ] || [ -z "$ANON_KEY" ]; then
  echo "error: couldn't read the local Supabase API URL / anon key from 'supabase status'." >&2
  echo "Run 'supabase status' yourself and check the local stack actually came up." >&2
  exit 1
fi

# Generated fresh every run — gitignored (matches .local convention), never
# committed, never touches web/.env.local (which may point at a hosted
# project) or the TEST/PROD/preview Cloudflare env scopes.
cat > web/.env.offline.local <<EOF
# Generated by scripts/offline.sh — do not edit, do not commit.
VITE_SUPABASE_URL=$API_URL
VITE_SUPABASE_ANON_KEY=$ANON_KEY
EOF

echo "Local Supabase is up: $API_URL"
echo "Data lives in the local Supabase Docker volume and persists across"
echo "restarts on its own. Run scripts/offline-backup.sh periodically for a"
echo "plain .sql file you can copy to a USB stick."
echo "Starting the app in offline mode (Ctrl-C stops the app; the local"
echo "Postgres stack keeps running — safe to rerun this script)."

# caffeinate keeps the Mac's display/system/idle sleep from kicking in while
# the offline server is running, so a brief lid-close mid-event doesn't drop
# the app. Best-effort: skip quietly if not on macOS.
if command -v caffeinate >/dev/null 2>&1; then
  exec caffeinate -dims npm --prefix web run dev:offline
else
  exec npm --prefix web run dev:offline
fi
